// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function StartNew(dir) {
  return window['go']['main']['App']['StartNew'](dir);
}

export function StartSession(id, dir) {
  return window['go']['main']['App']['StartSession'](id, dir);
}

export function TermKill() {
  return window['go']['main']['App']['TermKill']();
}

export function TermResize(cols, rows) {
  return window['go']['main']['App']['TermResize'](cols, rows);
}

export function TermWrite(b64) {
  return window['go']['main']['App']['TermWrite'](b64);
}
