// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetLastSession() {
  return window['go']['main']['App']['GetLastSession']();
}

export function SetLastSession(id) {
  return window['go']['main']['App']['SetLastSession'](id);
}

export function NotifyBeep() {
  return window['go']['main']['App']['NotifyBeep']();
}

export function DebugLog(msg) {
  return window['go']['main']['App']['DebugLog'](msg);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListHiddenSessions() {
  return window['go']['main']['App']['ListHiddenSessions']();
}

export function RenameSession(id, name) {
  return window['go']['main']['App']['RenameSession'](id, name);
}

export function DeleteSession(id) {
  return window['go']['main']['App']['DeleteSession'](id);
}

export function UnhideSession(id) {
  return window['go']['main']['App']['UnhideSession'](id);
}

export function StartNew(dir) {
  return window['go']['main']['App']['StartNew'](dir);
}

export function StartSession(id, dir) {
  return window['go']['main']['App']['StartSession'](id, dir);
}

export function TermKill(token) {
  return window['go']['main']['App']['TermKill'](token);
}

export function TermResize(token, cols, rows) {
  return window['go']['main']['App']['TermResize'](token, cols, rows);
}

export function TermWrite(token, b64) {
  return window['go']['main']['App']['TermWrite'](token, b64);
}